DELETE FROM REG_SERVICE_TYPE WHERE TYPE_ID='1';
DELETE FROM REG_SERVICE_TYPE WHERE TYPE_ID='2';
DELETE FROM ESB_VERSION WHERE ESB_VERSION='ESB8.6';

INSERT INTO REG_SERVICE_TYPE VALUES ('1', 'wsRoute', 'http://127.0.0.1:9099/org.gocom.esb.ws.route', '1', 'Y', '0', '1', '1', '2016-12-08 13:57:04', null);
INSERT INTO REG_SERVICE_TYPE VALUES ('2', 'restRoute', 'http://127.0.0.1:9099/org.gocom.esb.rest.route', '2', 'Y', '0', '2', '1', '2016-12-08 13:57:29', null);

INSERT INTO ESB_VERSION(ESB_VERSION) VALUES('ESB8.6');

insert into GOV_API_INFO values(1,'/black/query','POST');
insert into GOV_API_INFO values(2,'/black/create','POST');
insert into GOV_API_INFO values(3,'/black/update','POST');
insert into GOV_API_INFO values(4,'/black/delete','DELETE');
insert into GOV_API_INFO values(5,'/black/validate','POST');
insert into GOV_API_INFO values(6,'/black/export-data','POST');
insert into GOV_API_INFO values(7,'/relation/query','POST');
insert into GOV_API_INFO values(8,'/relation/create','POST');
insert into GOV_API_INFO values(9,'/relation/delete','DELETE');
insert into GOV_API_INFO values(10,'/relation/export-data','POST');
insert into GOV_API_INFO values(11,'/relation/authApi','POST');
insert into GOV_API_INFO values(12,'/flow/query','POST');
insert into GOV_API_INFO values(13,'/flow/create','POST');
insert into GOV_API_INFO values(14,'/flow/delete','DELETE');
insert into GOV_API_INFO values(15,'/flow/update','POST');
insert into GOV_API_INFO values(16,'/frequencys/query','POST');
insert into GOV_API_INFO values(17,'/frequencys/create','POST');
insert into GOV_API_INFO values(18,'/frequencys/delete','DELETE');
insert into GOV_API_INFO values(19,'/frequencys/update','POST');
insert into GOV_API_INFO values(20,'/timeout/query','POST');
insert into GOV_API_INFO values(21,'/timeout/create','POST');
insert into GOV_API_INFO values(22,'/timeout/delete','DELETE');
insert into GOV_API_INFO values(23,'/timeout/update','POST');
insert into GOV_API_INFO values(24,'/white/query','POST');
insert into GOV_API_INFO values(25,'/white/create','POST');
insert into GOV_API_INFO values(26,'/white/update','POST');
insert into GOV_API_INFO values(27,'/white/delete','DELETE');
insert into GOV_API_INFO values(28,'/white/validate','POST');
insert into GOV_API_INFO values(29,'/white/export-data','POST');
insert into GOV_API_INFO values(32,'/certificates/upload','POST');
insert into GOV_API_INFO values(33,'/certificates/{id}','DELETE');
insert into GOV_API_INFO values(34,'/certificates/{id}','GET');
insert into GOV_API_INFO values(35,'/certificates/page-search','POST');
insert into GOV_API_INFO values(36,'/certificates/generation','POST');
insert into GOV_API_INFO values(37,'/certificates/all','POST');
insert into GOV_API_INFO values(38,'/configuration/service/variable/proxy','GET');
insert into GOV_API_INFO values(39,'/configuration/service/variable/proxy','POST');
insert into GOV_API_INFO values(40,'/configuration/service/variable/business','GET');
insert into GOV_API_INFO values(41,'/configuration/service/variable/business','POST');
insert into GOV_API_INFO values(42,'/configuration/service/variable/media','GET');
insert into GOV_API_INFO values(43,'/configuration/service/variable/media','POST');
insert into GOV_API_INFO values(44,'/configuration/service/variable/transport','GET');
insert into GOV_API_INFO values(45,'/configuration/service/variable/transport','POST');
insert into GOV_API_INFO values(46,'/configuration/service/variable/endpoint','GET');
insert into GOV_API_INFO values(47,'/configuration/service/variable/endpoint','POST');
insert into GOV_API_INFO values(48,'/configuration/queue','GET');
insert into GOV_API_INFO values(49,'/configuration/queue','POST');
insert into GOV_API_INFO values(50,'/configuration/queue/clear','PUT');
insert into GOV_API_INFO values(51,'/configuration/service','POST');
insert into GOV_API_INFO values(52,'/configuration/service/wsdetail','POST');
insert into GOV_API_INFO values(53,'/configuration/service/jmsdetail','POST');
insert into GOV_API_INFO values(54,'/configuration/service/variable/root','GET');
insert into GOV_API_INFO values(55,'/configuration/service/variable/node','POST');
insert into GOV_API_INFO values(56,'/configuration/system','GET');
insert into GOV_API_INFO values(57,'/configuration/system','POST');
insert into GOV_API_INFO values(58,'/configuration/variable','GET');
insert into GOV_API_INFO values(59,'/configuration/variable/root','GET');
insert into GOV_API_INFO values(60,'/configuration/variable/node','POST');
insert into GOV_API_INFO values(61,'/configuration/variable','PUT');
insert into GOV_API_INFO values(62,'/deploy/upload','POST');
insert into GOV_API_INFO values(63,'/deploy/service','POST');
insert into GOV_API_INFO values(64,'/deploy/module/list','POST');
insert into GOV_API_INFO values(65,'/deploy/module/undeploy','POST');
insert into GOV_API_INFO values(66,'/server/list','POST');
insert into GOV_API_INFO values(67,'/server/license','POST');
insert into GOV_API_INFO values(68,'/server/{force:true|false}','POST');
insert into GOV_API_INFO values(69,'/server/{serverName}','DELETE');
insert into GOV_API_INFO values(70,'/server/{serverName}/sync','POST');
insert into GOV_API_INFO values(71,'/server/group/list','POST');
insert into GOV_API_INFO values(72,'/server/group','POST');
insert into GOV_API_INFO values(73,'/server/group/{groupName}','DELETE');
insert into GOV_API_INFO values(74,'/server/getServersAndGroups','GET');
insert into GOV_API_INFO values(75,'/server/getStandardServerGroupList','GET');
insert into GOV_API_INFO values(76,'/server/getStandardServerList','GET');
insert into GOV_API_INFO values(90,'/interface/queryInterface','POST');
insert into GOV_API_INFO values(91,'/interface/queryDomainName','GET');
insert into GOV_API_INFO values(92,'/interface/findAppNameByDomainName','POST');
insert into GOV_API_INFO values(93,'/interface/getServiceNameByAppCode','GET');
insert into GOV_API_INFO values(94,'/interface/getOperationNameByServiceCode','GET');
insert into GOV_API_INFO values(95,'/interface/export/interfaceQueryData','POST');
insert into GOV_API_INFO values(96,'/interface/findAppSystemByCodeName','POST');
insert into GOV_API_INFO values(97,'/interface/export/systemAppQueryData','POST');
insert into GOV_API_INFO values(98,'/interface/queryInterfaceDoc','POST');
insert into GOV_API_INFO values(99,'/interface/importInterfaceDoc','POST');
insert into GOV_API_INFO values(100,'/interface/exportDocTemplet','POST');
insert into GOV_API_INFO values(101,'/interface/updateInterfaceDocTemplet','POST');
insert into GOV_API_INFO values(102,'/interface/saveInterfaceDoc/{tempName:.+}','GET');
insert into GOV_API_INFO values(103,'/interface/exportInterfaceDoc','POST');
insert into GOV_API_INFO values(104,'/intersvc-statistics/svcchart','GET');
insert into GOV_API_INFO values(105,'/intersvc-statistics/svcsummary','POST');
insert into GOV_API_INFO values(106,'/intersvc-statistics/services','POST');
insert into GOV_API_INFO values(107,'/intersvc-statistics/operations','POST');
insert into GOV_API_INFO values(108,'/monitor/model/sources','GET');
insert into GOV_API_INFO values(109,'/monitor/model/names/{source:.+}','GET');
insert into GOV_API_INFO values(110,'/monitor/model/protocols/{source:.+}','GET');
insert into GOV_API_INFO values(111,'/monitor/model/list','POST');
insert into GOV_API_INFO values(112,'/monitor/model/transaction/{cid:.+}','GET');
insert into GOV_API_INFO values(113,'/monitor/model/trace-detail/{requestId:.+}','GET');
insert into GOV_API_INFO values(114,'/monitor/model/board/scatter','POST');
insert into GOV_API_INFO values(115,'/monitor/model/board/request','POST');
insert into GOV_API_INFO values(116,'/monitor/model/board/resource','POST');
insert into GOV_API_INFO values(117,'/monitor/model/board/mq','POST');
insert into GOV_API_INFO values(118,'/monitor/config/global','GET');
insert into GOV_API_INFO values(119,'/monitor/config/global','POST');
insert into GOV_API_INFO values(120,'/monitor/config/passageway','POST');
insert into GOV_API_INFO values(121,'/monitor/config/global/queryInterceptor','GET');
insert into GOV_API_INFO values(122,'/monitor/config/global/updateInterceptor','POST');
insert into GOV_API_INFO values(123,'/monitor/config/global/queryAlertFrequency','POST');
insert into GOV_API_INFO values(124,'/monitor/config/global/updateAlertFrequency','POST');
insert into GOV_API_INFO values(125,'/monitor/queue/message','GET');
insert into GOV_API_INFO values(126,'/sam/all-server-names','GET');
insert into GOV_API_INFO values(127,'/sam/service-codes/{appCode:.+}','GET');
insert into GOV_API_INFO values(128,'/sam/operations','POST');
insert into GOV_API_INFO values(129,'/sam/all-select-condition','GET');
insert into GOV_API_INFO values(130,'/server-board/request-histogram','POST');
insert into GOV_API_INFO values(131,'/server-board/scatter','POST');
insert into GOV_API_INFO values(132,'/server-board/resource','POST');
insert into GOV_API_INFO values(133,'/server-board/mq','POST');
insert into GOV_API_INFO values(134,'/service-statistics/provider/service-data','POST');
insert into GOV_API_INFO values(135,'/service-statistics/consumer/service-data','POST');
insert into GOV_API_INFO values(136,'/service-statistics/consumer/service-data/system','POST');
insert into GOV_API_INFO values(137,'/service-statistics/appSystem-data','POST');
insert into GOV_API_INFO values(138,'/service-statistics/call-data','POST');
insert into GOV_API_INFO values(139,'/service-statistics/transactions','POST');
insert into GOV_API_INFO values(140,'/monitor/tx/error/list','POST');
insert into GOV_API_INFO values(141,'/passageway/query','POST');
insert into GOV_API_INFO values(142,'/passageway/create','POST');
insert into GOV_API_INFO values(143,'/passageway/modify','POST');
insert into GOV_API_INFO values(144,'/passageway/delete/{passagewayIds}','DELETE');
insert into GOV_API_INFO values(145,'/passageway/queryById/{passagewayId}','GET');
insert into GOV_API_INFO values(146,'/passageway/queryByType/{passagewayType}','GET');
insert into GOV_API_INFO values(147,'/subscribe','POST');
insert into GOV_API_INFO values(148,'/subscribe/{id:.*}','DELETE');
insert into GOV_API_INFO values(149,'/subscribe','DELETE');
insert into GOV_API_INFO values(150,'/subscribe','PUT');
insert into GOV_API_INFO values(151,'/subscribe/query','POST');
insert into GOV_API_INFO values(152,'/subscribe/list','POST');
insert into GOV_API_INFO values(153,'/subscribe/startSubscribe','POST');
insert into GOV_API_INFO values(154,'/subscribe/stopSubscribe','POST');
insert into GOV_API_INFO values(155,'/subscribeLog/query','POST');
insert into GOV_API_INFO values(156,'/subscribeLog/reSend','POST');
insert into GOV_API_INFO values(157,'/subscriber','POST');
insert into GOV_API_INFO values(158,'/subscriber/{id:.*}','DELETE');
insert into GOV_API_INFO values(159,'/subscriber','DELETE');
insert into GOV_API_INFO values(160,'/subscriber','PUT');
insert into GOV_API_INFO values(161,'/subscriber/query','POST');
insert into GOV_API_INFO values(162,'/subscriber/list','POST');
insert into GOV_API_INFO values(163,'/subscribeStatistics/query','POST');
insert into GOV_API_INFO values(164,'/topicClassification','POST');
insert into GOV_API_INFO values(165,'/topicClassification/{id}','DELETE');
insert into GOV_API_INFO values(166,'/topicClassification','PUT');
insert into GOV_API_INFO values(167,'/topicClassification/list','GET');
insert into GOV_API_INFO values(168,'/operation','POST');
insert into GOV_API_INFO values(169,'/operation/service/{code:.*}','DELETE');
insert into GOV_API_INFO values(170,'/operation/{code:.*}','DELETE');
insert into GOV_API_INFO values(171,'/operation/batch','DELETE');
insert into GOV_API_INFO values(172,'/operation','PUT');
insert into GOV_API_INFO values(173,'/operation/query','POST');
insert into GOV_API_INFO values(174,'/operation/query/all','POST');
insert into GOV_API_INFO values(175,'/operation/{code:.*}','GET');
insert into GOV_API_INFO values(176,'/operation/ws/{code:.*}','GET');
insert into GOV_API_INFO values(177,'/operation/endpoint/{code:.*}','GET');
insert into GOV_API_INFO values(178,'/operation/verify/{code:.*}','GET');
insert into GOV_API_INFO values(179,'/operation/check/channel/{code:.*}','GET');
insert into GOV_API_INFO values(180,'/operation/exportQuery','POST');
insert into GOV_API_INFO values(181,'/operation/exportExtendQuery','POST');
insert into GOV_API_INFO values(182,'/operation/export/operationData','POST');
insert into GOV_API_INFO values(183,'/operation/import/operationData','POST');
insert into GOV_API_INFO values(184,'/operation/submit/operationData','POST');
insert into GOV_API_INFO values(185,'/operation/status','PUT');
insert into GOV_API_INFO values(186,'/service/importData','POST');
insert into GOV_API_INFO values(187,'/service','POST');
insert into GOV_API_INFO values(188,'/service/{code:.*}','DELETE');
insert into GOV_API_INFO values(189,'/service','DELETE');
insert into GOV_API_INFO values(190,'/service/system','DELETE');
insert into GOV_API_INFO values(191,'/service/domain','DELETE');
insert into GOV_API_INFO values(192,'/service','PUT');
insert into GOV_API_INFO values(193,'/service/query','POST');
insert into GOV_API_INFO values(194,'/service/info/{code:.*}','GET');
insert into GOV_API_INFO values(195,'/service/endpoint/check','POST');
insert into GOV_API_INFO values(196,'/service/endpoint','POST');
insert into GOV_API_INFO values(197,'/service/endpoint/query','POST');
insert into GOV_API_INFO values(198,'/service/query/endpoint','POST');
insert into GOV_API_INFO values(199,'/service/endpoint/{code:.*}/{id:.*}','GET');
insert into GOV_API_INFO values(200,'/service/wsdl','POST');
insert into GOV_API_INFO values(201,'/service/wsdl/url','POST');
insert into GOV_API_INFO values(202,'/service/wsdl/{wsServiceName:.*}/{wsPortName:.*}','GET');
insert into GOV_API_INFO values(203,'/service/verify/{code:.+}','GET');
insert into GOV_API_INFO values(204,'/service/verify/app/{code:.+}','GET');
insert into GOV_API_INFO values(205,'/service/import/onlineService','POST');
insert into GOV_API_INFO values(206,'/service/export/onlineService','GET');
insert into GOV_API_INFO values(207,'/service/export/onlineServiceDataZip','GET');
insert into GOV_API_INFO values(208,'/service/export/onlineServiceModelZip','GET');
insert into GOV_API_INFO values(209,'/service/upgrade/QuickRegistrationService','GET');
insert into GOV_API_INFO values(210,'/service/query/systems','POST');

insert into GOV_API_INFO values(211,'/service/querySamServiceStatus','POST');
insert into GOV_API_INFO values(212,'/service/wsdl/{code:.*}','GET');
insert into GOV_API_INFO values(213,'/service/wsdlport/{serviceId}','GET');
insert into GOV_API_INFO values(214,'/service/wsdlopeartion/{portId}','GET');
insert into GOV_API_INFO values(215,'/service/specs','POST');
insert into GOV_API_INFO values(216,'/service/specs/query','POST');
insert into GOV_API_INFO values(217,'/service/specs/info/{code:.*}','GET');
insert into GOV_API_INFO values(218,'/service/specs/keywordSearch','POST');
insert into GOV_API_INFO values(219,'/service/specs/serviceSpecsModel','GET');
insert into GOV_API_INFO values(220,'/service/specs/serviceSpecsImport','POST');
insert into GOV_API_INFO values(221,'/service/specs/serviceSpecsExport','GET');
insert into GOV_API_INFO values(222,'/service/specs/getProxyURI/{code:.*}','GET');

insert into GOV_API_INFO values(223,'/service/domain/tree','GET');
insert into GOV_API_INFO values(224,'/service/list/not/in/app','GET');
insert into GOV_API_INFO values(225,'/service/auto/deploy','PUT');
insert into GOV_API_INFO values(226,'/service/domain','POST');
insert into GOV_API_INFO values(227,'/service/domain','PUT');
insert into GOV_API_INFO values(228,'/service/domain/query','POST');
insert into GOV_API_INFO values(229,'/service/chk/domain','POST');
insert into GOV_API_INFO values(230,'/service/chk/system','POST');
insert into GOV_API_INFO values(231,'/service/chk/service','POST');
insert into GOV_API_INFO values(232,'/service/chk/operation','POST');
insert into GOV_API_INFO values(233,'/service/chk/domaincode/{domainCode:.*}','POST');
insert into GOV_API_INFO values(234,'/service/chk/appcode/{appCode:.*}','POST');
insert into GOV_API_INFO values(235,'/service/chk/servicecode/{serviceCode:.*}','POST');
insert into GOV_API_INFO values(236,'/service/chk/operationcode/{operationCode:.*}','POST');
insert into GOV_API_INFO values(237,'/service/system/{type}','POST');
insert into GOV_API_INFO values(238,'/service/system/check/{appcode:.*}','GET');
insert into GOV_API_INFO values(239,'/service/system','POST');
insert into GOV_API_INFO values(240,'/service/service/{type}','POST');
insert into GOV_API_INFO values(241,'/service/service','GET');
insert into GOV_API_INFO values(242,'/service/service','DELETE');
insert into GOV_API_INFO values(243,'/service/service/status','GET');
insert into GOV_API_INFO values(244,'/service/operation/{type}','POST');
insert into GOV_API_INFO values(245,'/service/operation','GET');
insert into GOV_API_INFO values(246,'/service/operation/status','GET');
insert into GOV_API_INFO values(247,'/service/operation','DELETE');
insert into GOV_API_INFO values(248,'/service/operation/{operationCode}/param','GET');
insert into GOV_API_INFO values(249,'/service/operation/{operationCode}/param"','POST');
insert into GOV_API_INFO values(250,'/service/operation/{operationCode}/param"','PUT');
insert into GOV_API_INFO values(251,'/service/system/{systemCode}/{status}','PUT');
insert into GOV_API_INFO values(252,'/service/service/num/{systemCode:.*}','GET');

insert into GOV_API_INFO values(258,'/user-accounts/{id}/password ','PUT');
insert into GOV_API_INFO values(259,'/user-accounts/{id}','DELETE');
insert into GOV_API_INFO values(261,'/user-accounts/{id}','PUT');
insert into GOV_API_INFO values(262,'/user-accounts/{id}','GET');
insert into GOV_API_INFO values(265,'/user-accounts','GET');
insert into GOV_API_INFO values(266,'/user-accounts','POST');
insert into GOV_API_INFO values(267,'/sync-data/records/latest','GET');
insert into GOV_API_INFO values(268,'/sync-data/records','GET');
insert into GOV_API_INFO values(269,'/sync-data','POST');
insert into GOV_API_INFO values(270,'/roles/{id}','DELETE');
insert into GOV_API_INFO values(271,'/roles/{id}','PUT');
insert into GOV_API_INFO values(272,'/roles/{id}','GET');
insert into GOV_API_INFO values(273,'/roles','POST');
insert into GOV_API_INFO values(274,'/roles','GET');
insert into GOV_API_INFO values(275,'/role-auths/{userAccountId}/granted-roles','GET');
insert into GOV_API_INFO values(276,'/role-auths/{userAccountId}/avariable-roles','GET');
insert into GOV_API_INFO values(277,'/role-auths/{userAccountId}','POST');
insert into GOV_API_INFO values(278,'/menus/{menuId}/children','GET');
insert into GOV_API_INFO values(279,'/menus/{menuId}','DELETE');
insert into GOV_API_INFO values(280,'/menus/{menuId}','PUT');
insert into GOV_API_INFO values(281,'/menus/{menuId}','GET');
insert into GOV_API_INFO values(282,'/menus','POST');
insert into GOV_API_INFO values(283,'/menus','GET');
insert into GOV_API_INFO values(284,'/menu-auths/{roleId}/granted-menus','GET');
insert into GOV_API_INFO values(285,'/menu-auths/{roleId}/available-menus','GET');
insert into GOV_API_INFO values(286,'/menu-auths','POST');
insert into GOV_API_INFO values(287,'/functions/{roleId}/granted-functions','GET');
insert into GOV_API_INFO values(288,'/functions/list/user/{user}','GET');
insert into GOV_API_INFO values(289,'/functions/functionCode/{code}','GET');
insert into GOV_API_INFO values(290,'/functions/available-functions','GET');
insert into GOV_API_INFO values(291,'/functions','POST');
insert into GOV_API_INFO values(292,'/audits/search','GET');
insert into GOV_API_INFO values(293,'/apps/{appId}','DELETE');
insert into GOV_API_INFO values(294,'/apps/{appId}','PUT');
insert into GOV_API_INFO values(295,'/apps/{appId}','GET');
insert into GOV_API_INFO values(296,'/apps','POST');
insert into GOV_API_INFO values(297,'/apps','GET');
insert into GOV_API_INFO values(298,'/queryLicenceContent','POST');
insert into GOV_API_INFO values(299,'/resend/queryFailInfo','POST');
insert into GOV_API_INFO values(300,'/resend/querySSMRend','POST');
insert into GOV_API_INFO values(301,'/resend/updateReState','POST');
insert into GOV_API_INFO values(302,'/resend/sendRequest','POST');
insert into GOV_API_INFO values(303,'/user-profile','GET');
insert into GOV_API_INFO values(304,'/user-profile','PUT');
insert into GOV_API_INFO values(305,'/user-profile/password','PUT');

insert into GOV_API_INFO values(341,'/monitor/board/statistics','POST');
insert into GOV_API_INFO values(342,'/monitor/board/avg-response','POST');
insert into GOV_API_INFO values(343,'/monitor/board/request','POST');
insert into GOV_API_INFO values(344,'/operation/statistic/operationsOfWeek','POST');

insert into GOV_API_INFO values(345,'/elastic/queryNodesInfo','POST');
insert into GOV_API_INFO values(346,'/elastic/queryIndicesInfo','POST');
insert into GOV_API_INFO values(347,'/elastic/deleteIndex','POST');

insert into GOV_API_INFO values(348,'/token/create','POST');
insert into GOV_API_INFO values(349,'/token/query','POST');
insert into GOV_API_INFO values(350,'/token/modify','POST');
insert into GOV_API_INFO values(351,'/token/delete','POST');

insert into GOV_API_INFO values(352,'/operation/export-operation-data','POST');
insert into GOV_API_INFO values(353,'/operation/export-alloperation-data','POST');
insert into GOV_API_INFO values(354,'/service/export-service-data','POST');
insert into GOV_API_INFO values(355,'/service/export-allservice-data','POST');
insert into GOV_API_INFO values(356,'/service/export-data','POST');
insert into GOV_API_INFO values(357,'/service/export-all-data','POST');

insert into GOV_API_INFO values(358,'/system-relation/getSystem','POST');

insert into GOV_API_INFO values(359,'/job/addServerJob','POST');
insert into GOV_API_INFO values(360,'/job/addInterInfo','POST');
insert into GOV_API_INFO values(361,'/job/addInterJob','POST');
insert into GOV_API_INFO values(362,'/job/startNow','POST');
insert into GOV_API_INFO values(363,'/job/reschedulejob','POST');
insert into GOV_API_INFO values(364,'/job/deletejob','POST');
insert into GOV_API_INFO values(365,'/job/queryjob','POST');
insert into GOV_API_INFO values(366,'/job/checkAllLog','POST');
insert into GOV_API_INFO values(367,'/job/checkLog','POST');
insert into GOV_API_INFO values(368,'/monitor/board/ScreenData','POST');
insert into GOV_API_INFO values(369,'/api/tables/${dataSourceName}','GET');
insert into GOV_API_INFO values(370,'/api/columns/${dataSourceName}/${tableName}','GET');
insert into GOV_API_INFO values(371,'/api/previewSql','POST');
insert into GOV_API_INFO values(372,'/monitor/config/queryGlobalConfig','POST');
insert into GOV_API_INFO values(373,'/datasource/page','POST');
insert into GOV_API_INFO values(374,'/datasource/saveOne','POST');
insert into GOV_API_INFO values(375,'/datasource/getOne','POST');
insert into GOV_API_INFO values(376,'/api/datasource/test','POST');
insert into GOV_API_INFO values(377,'/datasource/delete/${id}','POST');
insert into GOV_API_INFO values(378,'/messagequeue/saveOne','POST');
insert into GOV_API_INFO values(379,'/messagequeue/modify','POST');
insert into GOV_API_INFO values(380,'/messagequeue/delete/${id}','POST');
insert into GOV_API_INFO values(381,'/messagequeue/getOne','POST');
insert into GOV_API_INFO values(382,'/messagequeue/page','POST');
insert into GOV_API_INFO values(383,'/messagequeue/list','POST');
insert into GOV_API_INFO values(384,'/pubsubrelation/relation/page','POST');
insert into GOV_API_INFO values(385,'/pubsubrelation/page','POST');
insert into GOV_API_INFO values(386,'/pubsubrelation/publiber/page','POST');
insert into GOV_API_INFO values(387,'/pubsubrecord/page','POST');
insert into GOV_API_INFO values(388,'/provider/service-data/operation','POST');

INSERT INTO GLOBAL_MONITOR_CONFIG VALUES (1, 'MONITOR_CONFIG', 'alarmFreqEnable', '告警频率开关', 'false', null,  null);
INSERT INTO GLOBAL_MONITOR_CONFIG VALUES (2, 'MONITOR_CONFIG', 'alarmInterval', '时间间隔', '60', null,  null);
INSERT INTO GLOBAL_MONITOR_CONFIG VALUES (3, 'MONITOR_CONFIG', 'alarmTimes', '告警次数', '1', null,  null);
INSERT INTO GLOBAL_MONITOR_CONFIG VALUES (4, 'MONITOR_CONFIG', 'cpuAlarm', 'cpu告警', 'false', null,  null);
INSERT INTO GLOBAL_MONITOR_CONFIG VALUES (5, 'MONITOR_CONFIG', 'cpuThreshold', 'CPU阈值', '100', null,  null);
INSERT INTO GLOBAL_MONITOR_CONFIG VALUES (6, 'MONITOR_CONFIG', 'customAlarm', '告警参数开关', 'false', null,  null);
INSERT INTO GLOBAL_MONITOR_CONFIG VALUES (7, 'MONITOR_CONFIG', 'customAlarmParam', '告警参数', '', null,  null);
INSERT INTO GLOBAL_MONITOR_CONFIG VALUES (8, 'MONITOR_CONFIG', 'esAlarm', 'ES告警', 'false', null,  null);
INSERT INTO GLOBAL_MONITOR_CONFIG VALUES (9, 'MONITOR_CONFIG', 'esAlarmThreshold', 'ES磁盘告警阈值', '100', null,  null);
INSERT INTO GLOBAL_MONITOR_CONFIG VALUES (10, 'MONITOR_CONFIG', 'globalThreadPoolThreshold', '全局线程池大小', '100', null,  null);
INSERT INTO GLOBAL_MONITOR_CONFIG VALUES (11, 'MONITOR_CONFIG', 'globalThreadPoolThresholdAlarm', '全局线程池大小开关', 'false', null,  null);
INSERT INTO GLOBAL_MONITOR_CONFIG VALUES (12, 'MONITOR_CONFIG', 'globalThreadQueueThreshold', '全局线程池队列大小', '100', null,  null);
INSERT INTO GLOBAL_MONITOR_CONFIG VALUES (13, 'MONITOR_CONFIG', 'globalThreadQueueThresholdAlarm', '全局线程池队列大小开关', 'false', null,  null);
INSERT INTO GLOBAL_MONITOR_CONFIG VALUES (14, 'MONITOR_CONFIG', 'mail', '邮件地址', '', null,  null);
INSERT INTO GLOBAL_MONITOR_CONFIG VALUES (15, 'MONITOR_CONFIG', 'mailAlarm', '邮件告警', 'false', null,  null);
INSERT INTO GLOBAL_MONITOR_CONFIG VALUES (16, 'MONITOR_CONFIG', 'memoryAlarm', '内存告警', 'false', null,  null);
INSERT INTO GLOBAL_MONITOR_CONFIG VALUES (17, 'MONITOR_CONFIG', 'memoryThreshold', '内存阈值', '100', null,  null);
INSERT INTO GLOBAL_MONITOR_CONFIG VALUES (18, 'MONITOR_CONFIG', 'monitorTrace', '监控调用链', 'false', null,  null);
INSERT INTO GLOBAL_MONITOR_CONFIG VALUES (19, 'MONITOR_CONFIG', 'recordMessage', '记录报文体', 'false', null,  null);
INSERT INTO GLOBAL_MONITOR_CONFIG VALUES (20, 'MONITOR_CONFIG', 'mailHost', '邮箱网址', 'smtp.primeton.com', null,  null);
INSERT INTO GLOBAL_MONITOR_CONFIG VALUES (21, 'MONITOR_CONFIG', 'mailUser', '邮箱用户名', 'esb@primeton.com', null,  null);
INSERT INTO GLOBAL_MONITOR_CONFIG VALUES (22, 'MONITOR_CONFIG', 'mailPassword', '邮箱密码', 'ryOKQ7c1oq7LJVqm3W8mcg==', null,  null);
INSERT INTO GLOBAL_MONITOR_CONFIG VALUES (23, 'MONITOR_CONFIG', 'esThreadFreq', 'ES线程频率', '2000', null,  null);
INSERT INTO GLOBAL_MONITOR_CONFIG values (24, 'DATASOURCE_CONFIG', 'MySql', 'MySql', 'com.mysql.jdbc.Driver', null, null);
INSERT INTO GLOBAL_MONITOR_CONFIG values (25, 'DATASOURCE_CONFIG', 'Oracle', 'Oracle', 'oracle.jdbc.driver.OracleDriver', null, null);
INSERT INTO GLOBAL_MONITOR_CONFIG values (26, 'DATASOURCE_CONFIG', 'PostgresSQL', 'PostgresSQL', 'org.postgresql.Driver', null, null);
INSERT INTO GLOBAL_MONITOR_CONFIG values (40, 'DATASOURCE_CONFIG', 'SQLServer', 'SQLServer', 'com.microsoft.sqlserver.jdbc.SQLServerDriver', null, null);
INSERT INTO GLOBAL_MONITOR_CONFIG values (42, 'DATASOURCE_CONFIG', 'DM', 'DM', 'dm.jdbc.driver.DmDriver', null, null);
INSERT INTO GLOBAL_MONITOR_CONFIG values (43, 'DATASOURCE_CONFIG', 'openGaussDB', 'openGaussDB', 'org.opengauss.Driver', null, null);
INSERT INTO GLOBAL_MONITOR_CONFIG values (44, 'DATASOURCE_CONFIG', 'Gbase', 'Gbase', 'com.gbase.jdbc.Driver', null, null);
INSERT INTO GLOBAL_MONITOR_CONFIG values (45, 'DATASOURCE_CONFIG', 'HighGoDB', 'HighGoDB', 'com.highgo.jdbc.Driver', null, null);
INSERT INTO GLOBAL_MONITOR_CONFIG values (46, 'DATASOURCE_CONFIG', 'Kingbase8', 'Kingbase8', 'com.kingbase8.Driver', null, null);
INSERT INTO GLOBAL_MONITOR_CONFIG values (47, 'DATASOURCE_CONFIG', 'UXDB', 'UXDB', 'com.uxsino.uxdb.Driver', null, null);
INSERT INTO GLOBAL_MONITOR_CONFIG values (48, 'DATASOURCE_CONFIG', 'Oscar', 'Oscar', 'com.oscar.Driver', null, null);

INSERT INTO GLOBAL_MONITOR_CONFIG values (27, 'DATASOURCE_PREFIXURL', 'MySql', 'MySql', 'jdbc:mysql://', null, null);
INSERT INTO GLOBAL_MONITOR_CONFIG values (28, 'DATASOURCE_PREFIXURL', 'Oracle', 'Oracle', 'jdbc:oracle:thin:@', null, null);
INSERT INTO GLOBAL_MONITOR_CONFIG values (29, 'DATASOURCE_PREFIXURL', 'PostgresSQL', 'PostgresSQL', 'jdbc:postgresql://', null, null);
INSERT INTO GLOBAL_MONITOR_CONFIG values (50, 'DATASOURCE_PREFIXURL', 'SQLServer', 'SQLServer', 'jdbc:sqlserver://', null, null);
INSERT INTO GLOBAL_MONITOR_CONFIG values (51, 'DATASOURCE_PREFIXURL', 'DM', 'DM', 'jdbc:dm://', null, null);
INSERT INTO GLOBAL_MONITOR_CONFIG values (52, 'DATASOURCE_PREFIXURL', 'openGaussDB', 'openGaussDB', 'jdbc:opengauss://', null, null);
INSERT INTO GLOBAL_MONITOR_CONFIG values (53, 'DATASOURCE_PREFIXURL', 'Gbase', 'Gbase', 'jdbc:gbase://', null, null);
INSERT INTO GLOBAL_MONITOR_CONFIG values (54, 'DATASOURCE_PREFIXURL', 'HighGoDB', 'HighGoDB', 'jdbc:highgo://', null, null);
INSERT INTO GLOBAL_MONITOR_CONFIG values (55, 'DATASOURCE_PREFIXURL', 'Kingbase8', 'Kingbase8', 'jdbc:kingbase8://', null, null);
INSERT INTO GLOBAL_MONITOR_CONFIG values (56, 'DATASOURCE_PREFIXURL', 'UXDB', 'UXDB', 'jdbc:uxdb://', null, null);
INSERT INTO GLOBAL_MONITOR_CONFIG values (57, 'DATASOURCE_PREFIXURL', 'Oscar', 'Oscar', 'jdbc:oscar://', null, null);

INSERT INTO GLOBAL_MONITOR_CONFIG VALUES (58, 'INTERCEPTOR_STATUS', 'ServiceStatusControlInterceptor', '服务状态拦截器', 'false', null,  null);
INSERT INTO GLOBAL_MONITOR_CONFIG VALUES (59, 'INTERCEPTOR_STATUS', 'IpWhiteListControlInterceptor', '白名单拦截器', 'false', null,  null);
INSERT INTO GLOBAL_MONITOR_CONFIG VALUES (60, 'INTERCEPTOR_STATUS', 'IpBlackListControlInterceptor', '黑名单拦截器', 'false', null,  null);
INSERT INTO GLOBAL_MONITOR_CONFIG VALUES (61, 'INTERCEPTOR_STATUS', 'LoginControlInterceptor', '登陆控制拦截器', 'false', null,  null);
INSERT INTO GLOBAL_MONITOR_CONFIG VALUES (62, 'INTERCEPTOR_STATUS', 'AccessAuthorityControlInterceptor', '系统调用拦截器', 'false', null,  null);
INSERT INTO GLOBAL_MONITOR_CONFIG VALUES (63, 'INTERCEPTOR_STATUS', 'FlowcontrolInterceptor', '访问流拦截器', 'false', null,  null);
INSERT INTO GLOBAL_MONITOR_CONFIG VALUES (64, 'INTERCEPTOR_STATUS', 'FrequencyControlInterceptor', '访问频率拦截器', 'false', null,  null);
INSERT INTO GLOBAL_MONITOR_CONFIG VALUES (65, 'INTERCEPTOR_STATUS', 'ServiceTimeoutControlRequestInterceptor', '请求超时拦截器', 'false', null,  null);
INSERT INTO GLOBAL_MONITOR_CONFIG VALUES (66, 'INTERCEPTOR_STATUS', 'ServiceTimeoutControlReplyInterceptor', '响应超时拦截器', 'false', null,  null);
INSERT INTO GLOBAL_MONITOR_CONFIG VALUES (67, 'INTERCEPTOR_STATUS', 'ApiAccessInterceptor', '令牌管理拦截器', 'false', null,  null);

INSERT INTO um_role (UM_ROLE_NAME, UM_TENANT_ID) VALUES ('admin', 0);
INSERT INTO um_role (UM_ROLE_NAME, UM_TENANT_ID) VALUES ('everyone', 0);
INSERT INTO um_role (UM_ROLE_NAME, UM_TENANT_ID) VALUES ('wso2.anonymous.role', 0);

INSERT INTO um_user (UM_USER_NAME, UM_USER_PASSWORD, UM_SALT_VALUE, UM_REQUIRE_CHANGE, UM_CHANGED_TIME, UM_TENANT_ID) VALUES ('admin', 'hbUGirZNBQIomc9aLVlOSqHsqWkFEwjDR+qaKVxSgMI=\r\n', '40289e0c869b042701869b0427a30000', 0, getdate(), 0);
INSERT INTO um_user (UM_USER_NAME, UM_USER_PASSWORD, UM_SALT_VALUE, UM_REQUIRE_CHANGE, UM_CHANGED_TIME, UM_TENANT_ID) VALUES ('wso2.anonymous.user', 'i/vEklHgjneY3nzXObHG13rUfyLnZA7Ke1c7BMlqBJ8=\r\n', '40289e0c869b042701869b0427e40001', 0, getdate(), 0);

INSERT INTO um_user_role (UM_ROLE_ID, UM_USER_ID, UM_TENANT_ID) VALUES ( 2, 1, 0);
INSERT INTO um_user_role (UM_ROLE_ID, UM_USER_ID, UM_TENANT_ID) VALUES ( 1, 1, 0);
INSERT INTO um_user_role (UM_ROLE_ID, UM_USER_ID, UM_TENANT_ID) VALUES ( 3, 2, 0);